version: '3'
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile-test
    environment:
      - redis__host=redis
    links:
      - redis
    depends_on:
      - redis
  redis:
    image: redis:3
    ports:
      - 6379:6379